/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlodecredencias;

import javax.swing.JFrame;
import static controlodecredencias.ControlodeCredencias.dados;
import static controlodecredencias.ControlodeCredencias.fo;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author João
 */
public class ViaturaInterface extends javax.swing.JFrame implements Serializable{
    private static boolean adicionarviatura;
    /**
     * Creates new form ViaturaInterface
     */
    public ViaturaInterface(boolean adicionarViatura) {
        adicionarviatura = adicionarViatura;
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                closeconfirm();
            }
        });
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 150));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nº da Viatura");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 89, 29);

        if(!adicionarviatura)
        jTextField1.setVisible(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(140, 50, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        if(adicionarviatura)
        jButton2.setVisible(false);
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 90, 100, 23);

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 90, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        if(adicionarviatura)
        jLabel3.setText("Adicionar Viatura");
        else
        jLabel3.setText("Eliminar Viatura");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 0, 180, 60);

        String[] viaturasString = new String[dados.getListaViaturas().size()];
        for(int i=0;i<dados.getListaViaturas().size();i++){
            viaturasString[i]=String.valueOf(dados.getListaViaturas().get(i).getNumero());
        }
        if(adicionarviatura)
        jComboBox1.setVisible(false);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(viaturasString));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(140, 50, 70, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        if(!adicionarviatura)
        jButton5.setVisible(false);
        jButton5.setText("Inserir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(180, 90, 100, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void closeconfirm(){
        int k=JOptionPane.showConfirmDialog(null,"Tem a certeza que deseja sair?");
        if(k==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        JFrame menu =new Menu();
        menu.setVisible(true);
        menu.pack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int k=JOptionPane.showConfirmDialog(null,"Tem a certeza que deseja eliminar a viatura?");
        if(k==JOptionPane.YES_OPTION){
            removeViatura();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        int TeclaPressionada = evt.getKeyChar();
        if(TeclaPressionada == KeyEvent.VK_ENTER){
            jButton5.doClick();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        int TeclaPressionada = evt.getKeyChar();
        if(TeclaPressionada == KeyEvent.VK_ENTER){
            jButton2.doClick();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        int TeclaPressionada = evt.getKeyChar();
        if(TeclaPressionada == KeyEvent.VK_ENTER){
            jButton4.doClick();
        }
    }//GEN-LAST:event_jButton4KeyPressed
    
    private void removeViatura(){
        int posicao = jComboBox1.getSelectedIndex();
        if(posicao<0){
            JOptionPane.showMessageDialog(null,"Por favor, selecione uma viatura válida");
            return;
        }
        ArrayList<Viatura> viaturas = dados.getListaViaturas();
        viaturas.remove(posicao);
        dados.setListaViaturas(viaturas);
        AtualizaFicheiros();
        JOptionPane.showMessageDialog(null, "Viatura eliminada da base de dados com sucesso!");
        this.dispose();
    }
    private int verificaViatura(){
        ArrayList<Viatura> listaviaturas = dados.getListaViaturas();
        int numviatura;
        try{
            numviatura = Integer.parseInt(jTextField1.getText());
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira apenas algarismos!");
            return -1;
        }
        int i=0;
        if(listaviaturas.size()>0){
            for(i=0;i<listaviaturas.size();i++){
                if(listaviaturas.get(i).getNumero()==numviatura){
                    JOptionPane.showMessageDialog(null, "Essa viatura já existe na base de dados. Por favor, insira uma nova viatura!");
                    return -1;
                }
                if(listaviaturas.get(i).getNumero()>numviatura)
                    break;
            }
        }
        return i;
    }

    private void adicionarViatura(){
        int posicao = verificaViatura();
        ArrayList<Viatura> viaturas = dados.getListaViaturas();
        if(posicao<0){
            jTextField1.setText("");
            return;
        }
        viaturas.add(posicao,new Viatura(Integer.parseInt(jTextField1.getText())));
        dados.setListaViaturas(viaturas);
        AtualizaFicheiros();
        JOptionPane.showMessageDialog(null, "A viatura foi inserida na base de dados com sucesso!");
        this.dispose();
    }
    private void AtualizaFicheiros(){
        try{
            fo.abreEscrita("dados.bin");
            fo.escreveObjecto((BaseDados)dados);
            fo.fechaEscrita();
        }
        catch (Exception ex){         
            System.out.printf("Não foi possível escrever os dados no ficheiro! Exception found: %s\n",ex);
        }
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int k=JOptionPane.showConfirmDialog(null,"Tem a certeza que deseja adicionar a viatura?");
        if(k==JOptionPane.YES_OPTION){
            adicionarViatura();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        int TeclaPressionada = evt.getKeyChar();
        if(TeclaPressionada == KeyEvent.VK_ENTER){
            jButton5.doClick();
        }
       }//GEN-LAST:event_jButton5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViaturaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViaturaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViaturaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViaturaInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViaturaInterface(adicionarviatura).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
